# Generated by Django 3.1.6 on 2022-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20220131_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
