# Generated by Django 3.1.6 on 2022-01-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20220131_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
