# Generated by Django 3.1.6 on 2022-02-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_imagetest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetest',
            old_name='picture',
            new_name='file',
        ),
    ]
