# Generated by Django 3.1.6 on 2022-02-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20220202_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetest',
            name='height',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagetest',
            name='width',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
    ]
