# Generated by Django 3.1.6 on 2022-02-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_remove_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='parent_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
