# Generated by Django 3.1.6 on 2022-01-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='picture',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
