# Generated by Django 3.1.6 on 2022-02-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20220202_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetest',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
