# Generated by Django 3.1.6 on 2022-02-01 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20220202_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
