# Generated by Django 3.1.6 on 2022-02-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_remove_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTest',
        ),
    ]
