# Generated by Django 3.1.6 on 2022-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_delete_imagetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
